# Create a GitHub action to email a report from a file at 6 a.m. daily.
name: Email Report

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Email report
        run: |
          echo "Sending report to stakeholders"
          mail -s "Daily Report"